.PHONY: all build clean

all: build clean

build: 01

01:
	pdflatex mess_01.tex
	pdflatex mess_01.tex
	pdflatex mess_01.tex

clean:
	rm -f *.aux
	rm -f *.lof
	rm -f *.log
	rm -f *.lol
	rm -f *.lot
	rm -f *.out
	rm -f *.toc
